// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_oilTemp
void ui_oilTemp_screen_init(void);
void ui_event_oilTemp(lv_event_t * e);
lv_obj_t * ui_oilTemp;
void ui_event_oilTempArc(lv_event_t * e);
lv_obj_t * ui_oilTempArc;
lv_obj_t * ui_oilTempNum;


// SCREEN: ui_waterTemp
void ui_waterTemp_screen_init(void);
void ui_event_waterTemp(lv_event_t * e);
lv_obj_t * ui_waterTemp;
void ui_event_waterTempArc(lv_event_t * e);
lv_obj_t * ui_waterTempArc;
lv_obj_t * ui_waterTempNum;


// SCREEN: ui_Boost
void ui_Boost_screen_init(void);
void ui_event_Boost(lv_event_t * e);
lv_obj_t * ui_Boost;
void ui_event_boostBar(lv_event_t * e);
lv_obj_t * ui_boostBar;
lv_obj_t * ui_boostPressure;
void ui_event_Chart1(lv_event_t * e);
lv_obj_t * ui_Chart1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_oilTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_waterTemp, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_waterTemp_screen_init);
    }
}
void ui_event_oilTempArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_oilTempNum, target, "", "");
    }
}
void ui_event_waterTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Boost, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Boost_screen_init);
    }
}
void ui_event_waterTempArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_waterTempNum, target, "", "");
    }

}
void ui_event_Boost(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_oilTemp, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_oilTemp_screen_init);
    }
}
void ui_event_boostBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_oilTemp, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_oilTemp_screen_init);
    }
}


///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_oilTemp_screen_init();
    ui_waterTemp_screen_init();
    ui_Boost_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_oilTemp);
}
