// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_coolantTemp
void ui_coolantTemp_screen_init(void);
void ui_event_coolantTemp(lv_event_t * e);
lv_obj_t * ui_coolantTemp;
lv_obj_t * ui_coolantArc;
lv_obj_t * ui_coolantVal;
lv_obj_t * ui_coolantUnit;
lv_obj_t * ui_coolantLabel;


// SCREEN: ui_boostPressure
void ui_boostPressure_screen_init(void);
void ui_event_boostPressure(lv_event_t * e);
lv_obj_t * ui_boostPressure;
lv_obj_t * ui_boostArc;
lv_obj_t * ui_boostVal;
lv_obj_t * ui_boostUnit;
lv_obj_t * ui_boostLabel;


// SCREEN: ui_intakeTemp
void ui_intakeTemp_screen_init(void);
void ui_event_intakeTemp(lv_event_t * e);
lv_obj_t * ui_intakeTemp;
lv_obj_t * ui_iatArc;
lv_obj_t * ui_iatVal;
lv_obj_t * ui_iatUnit;
lv_obj_t * ui_iatLabel;


// SCREEN: ui_moduleVoltage
void ui_moduleVoltage_screen_init(void);
void ui_event_moduleVoltage(lv_event_t * e);
lv_obj_t * ui_moduleVoltage;
lv_obj_t * ui_voltageArc;
lv_obj_t * ui_voltageVal;
lv_obj_t * ui_voltageUnit;
lv_obj_t * ui_voltageLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_coolantTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_boostPressure, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_boostPressure_screen_init);
    }
}
void ui_event_boostPressure(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_intakeTemp, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_intakeTemp_screen_init);
    }
}
void ui_event_intakeTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_moduleVoltage, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_moduleVoltage_screen_init);
    }
}
void ui_event_moduleVoltage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_coolantTemp, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_coolantTemp_screen_init);
    }
}


///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_coolantTemp_screen_init();
    ui_boostPressure_screen_init();
    ui_intakeTemp_screen_init();
    ui_moduleVoltage_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_coolantTemp);
}
