// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Boost_screen_init(void)
{
    ui_Boost = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Boost, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Boost, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Boost, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Boost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_boostBar = lv_bar_create(ui_Boost);
    lv_bar_set_range(ui_boostBar, -500, 2000);
    lv_bar_set_value(ui_boostBar, 500, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_boostBar, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_boostBar, 60);
    lv_obj_set_height(ui_boostBar, 80);
    lv_obj_set_align(ui_boostBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_boostBar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_boostBar, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_boostBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_boostBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_boostBar, lv_color_hex(0x00A112), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_boostBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_boostPressure = lv_label_create(ui_Boost);
    lv_obj_set_width(ui_boostPressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boostPressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_boostPressure, LV_ALIGN_CENTER);
    lv_label_set_text(ui_boostPressure, "0.4");
    lv_obj_clear_flag(ui_boostPressure, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_boostPressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_boostPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_boostPressure, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_boostPressure, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_boostBar, ui_event_boostBar, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Boost, ui_event_Boost, LV_EVENT_ALL, NULL);

}
