// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_coolantTemp_screen_init(void)
{
    ui_coolantTemp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_coolantTemp, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_coolantTemp, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_coolantTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_coolantTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolantArc = lv_arc_create(ui_coolantTemp);
    lv_obj_set_width(ui_coolantArc, 210);
    lv_obj_set_height(ui_coolantArc, 210);
    lv_obj_set_align(ui_coolantArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_coolantArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_coolantArc, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_range(ui_coolantArc, -40, 215);
    lv_arc_set_bg_angles(ui_coolantArc, 135, 45);
    lv_obj_set_style_arc_color(ui_coolantArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_coolantArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_coolantArc, lv_color_hex(0x00A3E6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_coolantArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_coolantArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_coolantArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_coolantArc, lv_color_hex(0xFFE800), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_coolantArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_coolantVal = lv_label_create(ui_coolantTemp);
    lv_obj_set_width(ui_coolantVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolantVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_coolantVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coolantVal, "---");
    lv_obj_clear_flag(ui_coolantVal, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_coolantVal, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_coolantVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolantVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_coolantVal, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coolantVal, &ui_font_center60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolantUnit = lv_label_create(ui_coolantTemp);
    lv_obj_set_width(ui_coolantUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolantUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolantUnit, 0);
    lv_obj_set_y(ui_coolantUnit, 100);
    lv_obj_set_align(ui_coolantUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coolantUnit, "degC");
    lv_obj_clear_flag(ui_coolantUnit, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_coolantUnit, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_coolantUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolantUnit, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_coolantUnit, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coolantUnit, &ui_font_unit16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolantLabel = lv_label_create(ui_coolantTemp);
    lv_obj_set_width(ui_coolantLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolantLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolantLabel, 0);
    lv_obj_set_y(ui_coolantLabel, 38);
    lv_obj_set_align(ui_coolantLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coolantLabel, "COOLANT");
    lv_obj_set_style_text_color(ui_coolantLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolantLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coolantLabel, &ui_font_unit16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_coolantTemp, ui_event_coolantTemp, LV_EVENT_ALL, NULL);

}
