// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_intakeTemp_screen_init(void)
{
    ui_intakeTemp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_intakeTemp, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_intakeTemp, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_intakeTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_intakeTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iatArc = lv_arc_create(ui_intakeTemp);
    lv_obj_set_width(ui_iatArc, 210);
    lv_obj_set_height(ui_iatArc, 210);
    lv_obj_set_align(ui_iatArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_iatArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_iatArc, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_range(ui_iatArc, -40, 215);
    lv_arc_set_value(ui_iatArc, 23);
    lv_arc_set_bg_angles(ui_iatArc, 135, 45);
    lv_obj_set_style_arc_color(ui_iatArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_iatArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_iatArc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_iatArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_iatArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_iatArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_iatArc, lv_color_hex(0xFFE800), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_iatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_iatVal = lv_label_create(ui_intakeTemp);
    lv_obj_set_width(ui_iatVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iatVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_iatVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iatVal, "---");
    lv_obj_clear_flag(ui_iatVal, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_iatVal, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_iatVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iatVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_iatVal, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iatVal, &ui_font_center60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iatUnit = lv_label_create(ui_intakeTemp);
    lv_obj_set_width(ui_iatUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iatUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iatUnit, 0);
    lv_obj_set_y(ui_iatUnit, 100);
    lv_obj_set_align(ui_iatUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iatUnit, "degC");
    lv_obj_clear_flag(ui_iatUnit, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_iatUnit, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_iatUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iatUnit, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_iatUnit, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iatUnit, &ui_font_unit16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iatLabel = lv_label_create(ui_intakeTemp);
    lv_obj_set_width(ui_iatLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iatLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iatLabel, 0);
    lv_obj_set_y(ui_iatLabel, 38);
    lv_obj_set_align(ui_iatLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iatLabel, "IAT");
    lv_obj_set_style_text_color(ui_iatLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iatLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iatLabel, &ui_font_unit16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_intakeTemp, ui_event_intakeTemp, LV_EVENT_ALL, NULL);

}
