// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_moduleVoltage_screen_init(void)
{
    ui_moduleVoltage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_moduleVoltage, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_moduleVoltage, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_moduleVoltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_moduleVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltageArc = lv_arc_create(ui_moduleVoltage);
    lv_obj_set_width(ui_voltageArc, 210);
    lv_obj_set_height(ui_voltageArc, 210);
    lv_obj_set_align(ui_voltageArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_voltageArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_voltageArc, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_range(ui_voltageArc, 6000, 18000);
    lv_arc_set_value(ui_voltageArc, 10000);
    lv_arc_set_bg_angles(ui_voltageArc, 135, 45);
    lv_obj_set_style_arc_color(ui_voltageArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_voltageArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_voltageArc, lv_color_hex(0x1AFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_voltageArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_voltageArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_voltageArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_voltageArc, lv_color_hex(0xFFE800), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_voltageArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_voltageVal = lv_label_create(ui_moduleVoltage);
    lv_obj_set_width(ui_voltageVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltageVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_voltageVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltageVal, "--.-");
    lv_obj_clear_flag(ui_voltageVal, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_voltageVal, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_voltageVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltageVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_voltageVal, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltageVal, &ui_font_center60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltageUnit = lv_label_create(ui_moduleVoltage);
    lv_obj_set_width(ui_voltageUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltageUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltageUnit, 0);
    lv_obj_set_y(ui_voltageUnit, 100);
    lv_obj_set_align(ui_voltageUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltageUnit, "V");
    lv_obj_clear_flag(ui_voltageUnit, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_voltageUnit, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_voltageUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltageUnit, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_voltageUnit, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltageUnit, &ui_font_unit16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltageLabel = lv_label_create(ui_moduleVoltage);
    lv_obj_set_width(ui_voltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltageLabel, 0);
    lv_obj_set_y(ui_voltageLabel, 38);
    lv_obj_set_align(ui_voltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltageLabel, "BATTERY");
    lv_obj_set_style_text_color(ui_voltageLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltageLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltageLabel, &ui_font_unit16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_moduleVoltage, ui_event_moduleVoltage, LV_EVENT_ALL, NULL);

}
