// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_oilTemp_screen_init(void)
{
    ui_oilTemp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_oilTemp, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_oilTemp, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_oilTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilTempArc = lv_arc_create(ui_oilTemp);
    lv_obj_set_width(ui_oilTempArc, 210);
    lv_obj_set_height(ui_oilTempArc, 210);
    lv_obj_set_align(ui_oilTempArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_oilTempArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_oilTempArc, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_range(ui_oilTempArc, 0, 150);
    lv_arc_set_value(ui_oilTempArc, 75);
    lv_arc_set_bg_angles(ui_oilTempArc, 135, 45);
    lv_obj_set_style_arc_color(ui_oilTempArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_oilTempArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_oilTempArc, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_oilTempArc, lv_color_hex(0xE67300), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_oilTempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_oilTempArc, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_oilTempArc, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_oilTempArc, lv_color_hex(0xFFE800), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilTempArc, 127, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_oilTempArc, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_oilTempArc, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_oilTempArc, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_oilTempArc, -5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_oilTempNum = lv_label_create(ui_oilTemp);
    lv_obj_set_width(ui_oilTempNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilTempNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_oilTempNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oilTempNum, "00");
    lv_obj_clear_flag(ui_oilTempNum, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_oilTempNum, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_oilTempNum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilTempNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_oilTempNum, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilTempNum, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_oilTempArc, ui_event_oilTempArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oilTemp, ui_event_oilTemp, LV_EVENT_ALL, NULL);

}
