// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_waterTemp_screen_init(void)
{
    ui_waterTemp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_waterTemp, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_waterTemp, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_waterTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waterTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waterTempArc = lv_arc_create(ui_waterTemp);
    lv_obj_set_width(ui_waterTempArc, 210);
    lv_obj_set_height(ui_waterTempArc, 210);
    lv_obj_set_align(ui_waterTempArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_waterTempArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_waterTempArc, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_range(ui_waterTempArc, 0, 150);
    lv_arc_set_value(ui_waterTempArc, 12);
    lv_arc_set_bg_angles(ui_waterTempArc, 135, 45);
    lv_obj_set_style_arc_color(ui_waterTempArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_waterTempArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_waterTempArc, lv_color_hex(0x00A3E6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_waterTempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_waterTempArc, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_waterTempArc, 200, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_waterTempArc, lv_color_hex(0xFFE800), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waterTempArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_waterTempNum = lv_label_create(ui_waterTemp);
    lv_obj_set_width(ui_waterTempNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waterTempNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_waterTempNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waterTempNum, "00");
    lv_obj_clear_flag(ui_waterTempNum, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_waterTempNum, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_waterTempNum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_waterTempNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_waterTempNum, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_waterTempNum, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_waterTempArc, ui_event_waterTempArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_waterTemp, ui_event_waterTemp, LV_EVENT_ALL, NULL);

}
